sudo: false

language: java
jdk: oraclejdk8

jobs:
  include:
    - stage: junit5-maven-consumer
      script: cd $TRAVIS_BUILD_DIR/junit5-maven-consumer && ./mvnw test
    - stage: junit5-gradle-consumer
      script: cd $TRAVIS_BUILD_DIR/junit5-gradle-consumer && ./gradlew test
    - stage: junit5-mockito-extension
      script: cd $TRAVIS_BUILD_DIR/junit5-mockito-extension && ./gradlew test
    - stage: junit5-vanilla-gradle
      script: cd $TRAVIS_BUILD_DIR/junit5-mockito-extension && ./gradlew test
