sudo: false

language: java
jdk: oraclejdk8

jobs:
  include:
# vanilla
    - stage: vanilla
      env: TOOL='Maven'
      script: cd $TRAVIS_BUILD_DIR/junit5-vanilla-maven && ./mvnw test
    - stage: vanilla
      env: TOOL='Gradle'
      script: cd $TRAVIS_BUILD_DIR/junit5-vanilla-gradle && ./gradlew test --console plain
    - stage: vanilla
      jdk: oraclejdk9
      env: TOPIC='Java Platform Module System'
      script: cd $TRAVIS_BUILD_DIR/junit5-vanilla-modules && ./build.jsh
# consumer
    - stage: consumer
      env: TOOL='Maven'
      script: cd $TRAVIS_BUILD_DIR/junit5-maven-consumer && ./mvnw test
    - stage: consumer
      env: TOOL='Gradle'
      script: cd $TRAVIS_BUILD_DIR/junit5-gradle-consumer && ./gradlew test --console plain
    - stage: consumer
      env: TOPIC='Mockito Extension'
      script: cd $TRAVIS_BUILD_DIR/junit5-mockito-extension && ./gradlew test --console plain
# java 9 and higher
    - stage: java-9
      jdk: oraclejdk9
      env: TOPIC='Ice Cream Machine'
      script: cd $TRAVIS_BUILD_DIR/junit5-java9-engine && ./gradlew check --console plain
    - stage: java-9
      jdk: oraclejdk9
      env: TOOL='Maven'
      script: cd $TRAVIS_BUILD_DIR/junit5-maven-consumer && ./mvnw test
# snapshot -- use current junit master branch
    - stage: snapshot
      env: TOOL='Gradle'
      script: cd $TRAVIS_BUILD_DIR/junit5-vanilla-gradle && ./gradlew test --console plain --build-file build-SNAPSHOT.gradle
    - stage: snapshot
      env: TOOL='Maven'
      script: cd $TRAVIS_BUILD_DIR/junit5-vanilla-maven && ./mvnw test --file pom-SNAPSHOT.xml
# all samples, one-shot
    - stage: all
      env: TOPIC='Build all samples'
      script: install: . ./src/install-jdk.sh && ./build-all-samples.jsh
